"""empty message

Revision ID: 82afff41ee3d
Revises: ddc84814d4db
Create Date: 2023-06-05 15:39:19.125080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82afff41ee3d'
down_revision = 'ddc84814d4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=230),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.String(length=230),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
